name: Weather Fetch Cron

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  fetch-weather:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install node-fetch@2

      - name: Run Fetch
        env:
          WP_ENDPOINT: ${{ secrets.WP_ENDPOINT }}
          CWF_SECRET: ${{ secrets.CWF_SECRET }}
        run: node fetch.js
